export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  KAFKA_CONNECTION_FAILED = 'KAFKA_CONNECTION_FAILED',
  KAFKA_PUBLISH_FAILED = 'KAFKA_PUBLISH_FAILED',
  ANALYTICS_PUBLISH_FAILED = 'ANALYTICS_PUBLISH_FAILED',
}
