services:
  backend:
    build: .
    container_name: iot_backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/sensores_db
      JWT_SECRET: super_secret_key
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: sensores_mongo
    ports:
      - "27017:27017"
    volumes:
      - sensores_mongo_data:/data/db
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  sensores_mongo_data:

