import { EventType } from '../common/events/event-types';

export const KAFKA_TOPICS = {
  TELEMETRY_RECEIVED: EventType.TELEMETRY_RECEIVED,
  ALERT_GENERATED: EventType.ALERT_GENERATED,
} as const;

  /*SENSOR_OFFLINE: EventType.SENSOR_OFFLINE,
  LOW_BATTERY: EventType.LOW_BATTERY,

  TEMPERATURE_OUT_OF_RANGE: EventType.TEMPERATURE_OUT_OF_RANGE,
  GLUCOSE_OUT_OF_RANGE: EventType.GLUCOSE_OUT_OF_RANGE,
  OXYGEN_SATURATION_LOW: EventType.OXYGEN_SATURATION_LOW,
  HEART_RATE_OUT_OF_RANGE: EventType.HEART_RATE_OUT_OF_RANGE,
  BLOOD_PRESSURE_HIGH: EventType.BLOOD_PRESSURE_HIGH,
} as const;
*/